development:
  domain: localhost:3000
  paperclip_identify_path: /opt/local/bin/
  db_cameras_path: etc/db_cameras/
  db_cameras_mad: cameras_mad.csv
  db_cameras_bcn: cameras_bcn.csv
  google_api_key: 'ABQIAAAAlqHVgda1Vyq8JQWd9v1BVRTZe2NynXf9TfusV2EJKPopn2_KfxQ2OFHVA5G6E08qVGyjqI6Ga6221A'
  default_lat: 40.4166909
  default_lng: -3.7003454
  password: wadus

test:
  domain: test.host
  paperclip_identify_path: /opt/local/bin/
  db_cameras_path: tmp/db_cameras/
  db_cameras_mad: cameras_mad.csv
  db_cameras_bcn: cameras_bcn.csv
  google_api_key: 'ABQIAAAAlqHVgda1Vyq8JQWd9v1BVRTZe2NynXf9TfusV2EJKPopn2_KfxQ2OFHVA5G6E08qVGyjqI6Ga6221A'
  default_lat: 40.4166909
  default_lng: -3.7003454
  password: wadus
  
production:
  domain: example.com
  paperclip_identify_path: /usr/bin/
  db_cameras_path: etc/db_cameras/
  db_cameras_mad: cameras_mad.csv
  db_cameras_bcn: cameras_bcn.csv
  google_api_key: 'ABQIAAAAlqHVgda1Vyq8JQWd9v1BVRTZe2NynXf9TfusV2EJKPopn2_KfxQ2OFHVA5G6E08qVGyjqI6Ga6221A'
  default_lat: 40.4166909
  default_lng: -3.7003454
  password: wadus
