test:
  adapter: sqlite3
  database: db/test.sqlite3

development:
  adapter: sqlite3
  database: db/development.sqlite3
    
production:
  adapter: mysql 
  encoding: utf8 
  database: ojosciudad
  username: ojosciudad 
  password: ojosciudad
