development:
  adapter: mysql 
  encoding: utf8 
  database: ojosciudad_development
  username: ojosciudad 
  password: ojosciudad

test:
  adapter: mysql 
  encoding: utf8 
  database: ojosciudad_test
  username: ojosciudad 
  password: ojosciudad
    
production:
  adapter: mysql 
  encoding: utf8 
  database: ojosciudad
  username: ojosciudad 
  password: ojosciudad
